WebApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Contracts.App;
using DAL.Contracts.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.EF.App;
using DAL.EF.App.Repositories;
using Microsoft.AspNetCore.Authorization;
using Courses = BLL.DTO.Courses;
#pragma warning disable 1591

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class CoursesController : Controller
    {
        
        private readonly IAppBLL _bll;

        public CoursesController(IAppBLL bll)
        {
            
            _bll = bll;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {

            var vm = await _bll.CoursesService.AllAsync();
            return View(vm);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = await _bll.CoursesService.FindAsync(id.Value);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CoursesDTO/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BLL.DTO.Courses courses)
        {
            if (ModelState.IsValid)
            {

                _bll.CoursesService.Add(courses);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(courses);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = await _bll.CoursesService.FindAsync(id.Value);
            if (courses == null)
            {
                return NotFound();
            }
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Courses courses)
        {
            if (id != courses.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _bll.CoursesService.Update(courses);

                await _bll.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            return View(courses);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = await _bll.CoursesService.FindAsync(id.Value);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.CoursesService.RemoveAsync(id);
            
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/RemaindersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.Contracts.App;
using DAL.Contracts.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.EF.App;
using DAL.EF.App.Repositories;
using Domain.App;
using Domain.App.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using WebApp.ViewModels.Admin;
#pragma warning disable 1591

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class RemaindersController : Controller
    {
        
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        
        public RemaindersController(IAppBLL bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // GET: Remainders
        public async Task<IActionResult> Index()
        {
            var vm = await _bll.RemaindersService.AllAsync();

            return View(vm);

        }

        // GET: Remainders/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var remainders = await _bll.RemaindersService.FindAsync(id.Value);
            if (remainders == null)
            {
                return NotFound();
            }

            return View(remainders);
        }

        // GET: Remainders/Create
        public Task<IActionResult> Create()
        {
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.FullName));
            var vm = new RemaindersVM();
            vm.RemaindersUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            return Task.FromResult<IActionResult>(View(vm));
        }

        // POST: Remainders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RemaindersVM remainders)
        {
            if (ModelState.IsValid)
            {
                _bll.RemaindersService.Add(remainders.RemaindersVm);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.FullName), remainders.AppUserId);
            var vm = new RemaindersVM();
            vm.RemaindersUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            return View(vm);
        }

        // GET: Remainders/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var remainders = await _bll.RemaindersService.FindAsync(id.Value);
            if (remainders == null)
            {
                return NotFound();
            }
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.FullName), remainders.AppUserId);
            var vm = new RemaindersVM()
            {
                RemaindersVm = remainders
            };
            vm.RemaindersUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            return View(vm);
        }

        // POST: Remainders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, RemaindersVM remainders)
        {
            if (id != remainders.RemaindersVm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                _bll.RemaindersService.Update(remainders.RemaindersVm);
                await _bll.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.FullName), remainders.AppUserId);
            var vm = new RemaindersVM();
            vm.RemaindersUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            return View(vm);
        }

        // GET: Remainders/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var remainders = await _bll.RemaindersService.FindAsync(id.Value);
            if (remainders == null)
            {
                return NotFound();
            }

            return View(remainders);
        }

        // POST: Remainders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.RemaindersService.RemoveAsync(id);
            
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/StudyGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BLL.Contracts.App;
using DAL.Contracts.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.EF.App;
using DAL.EF.App.Repositories;
using Domain.App;
using Domain.App.Identity;
using Helpers.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using WebApp.ViewModels.Admin;
#pragma warning disable 1591

namespace WebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class StudyGroupsController : Controller
    {
        
        private readonly IAppBLL _bll;
        private readonly UserManager<AppUser> _userManager;
        
        public StudyGroupsController(IAppBLL bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }
        
        // GET: StudyGroups/MyStudyGroups
        public async Task<IActionResult> MyStudyGroups()
        {
            var userStudyGroups = await _bll.StudyGroupsService.AllAsync();
            return View(userStudyGroups);
        }

        // GET: StudyGroups
        public async Task<IActionResult> Index()
        {
            var vm = await _bll.StudyGroupsService.AllAsync();
            return View(vm);
        }

        // GET: StudyGroups/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studyGroups = await _bll.StudyGroupsService.FindAsync(id.Value);
            
            if (studyGroups == null)
            {
                return NotFound();
            }

            return View(studyGroups);
        }

        // GET: StudyGroups/Create
        public async Task<IActionResult> Create()
        {
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.Email));
            //ViewData["CourseId"] = new SelectList(_context.Courses, nameof(Courses.Id), nameof(Courses.CourseName));
            var vm = new StudyGroupsVM();
            vm.StudyGroupsUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            vm.StudyGroupsCoursesSelectList = new SelectList(await _bll.CoursesService.AllAsync(),
                nameof(vm.StudyGroupsVm.Course.Id),
                nameof(vm.StudyGroupsVm.Course.CourseName));
            return View(vm);
        }

        // POST: StudyGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StudyGroupsVM studyGroups)
        {
            studyGroups.StudyGroupsVm.AppUserId = User.GetUserId();
            if (ModelState.IsValid)
            {
                _bll.StudyGroupsService.Add(studyGroups.StudyGroupsVm);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CourseId"] = new SelectList(_context.Courses, nameof(Courses.Id), nameof(Courses.CourseName), studyGroups.CourseId);
            var vm = new StudyGroupsVM();
            vm.StudyGroupsUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            vm.StudyGroupsCoursesSelectList = new SelectList(await _bll.CoursesService.AllAsync(),
                nameof(vm.StudyGroupsVm.Course.Id),
                nameof(vm.StudyGroupsVm.Course.CourseName));
            return View(vm);
        }

        // GET: StudyGroups/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studyGroups = await _bll.StudyGroupsService.FindAsync(id.Value);
            if (studyGroups == null)
            {
                return NotFound();
            }
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.Email), studyGroups.AppUserId);
            //ViewData["CourseId"] = new SelectList(_context.Courses, nameof(Courses.Id), nameof(Courses.CourseName), studyGroups.CourseId);
            var vm = new StudyGroupsVM()
            {
                StudyGroupsVm = studyGroups
            };
            vm.StudyGroupsUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            vm.StudyGroupsCoursesSelectList = new SelectList(await _bll.CoursesService.AllAsync(),
                nameof(vm.StudyGroupsVm.Course.Id),
                nameof(vm.StudyGroupsVm.Course.CourseName));
            return View(vm);
        }

        // POST: StudyGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, StudyGroupsVM studyGroups)
        {
            if (id != studyGroups.StudyGroupsVm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _bll.StudyGroupsService.Update(studyGroups.StudyGroupsVm);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AppUserId"] = new SelectList(_userManager.Users, nameof(AppUser.Id), nameof(AppUser.Email), studyGroups.AppUserId);
            //ViewData["CourseId"] = new SelectList(_context.Courses, nameof(Courses.Id), nameof(Courses.CourseName), studyGroups.CourseId);
            var vm = new StudyGroupsVM();
            vm.StudyGroupsUserSelectList = new SelectList(_userManager.Users,
                nameof(vm.AppUser.Id),
                nameof(vm.AppUser.FirstName));
            vm.StudyGroupsCoursesSelectList = new SelectList(await _bll.CoursesService.AllAsync(),
                nameof(vm.StudyGroupsVm.Course.Id),
                nameof(vm.StudyGroupsVm.Course.CourseName));
            return View(vm);
        }

        // GET: StudyGroups/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studyGroups = await _bll.StudyGroupsService.FindAsync(id.Value);
            
            if (studyGroups == null)
            {
                return NotFound();
            }

            return View(studyGroups);
        }

        // POST: StudyGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.StudyGroupsService.RemoveAsync(id);
            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Views/Shared/_LanguageSelectionPartial.cshtml
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@{
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new {Value = c.Name, Text = c.NativeName});
}


<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Language
    </a>
    <ul class="dropdown-menu">
        @foreach (var item in cultureItems)
        {
            <li>
                <a class="dropdown-item"
                   asp-area=""
                   asp-controller="Home"
                   asp-action="SetLanguage"
                   asp-route-culture="@item.Value"
                   asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                    @item.Text
                </a>
            </li>
        }
    </ul>
</li>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
@if (User.IsInRole("admin")) {
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">W</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="GroupJoinRequests" asp-action="Index">GroupJoinRequests</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="GroupMeetings" asp-action="Index">GroupMeetings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="GroupMessages" asp-action="Index">GroupMessages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Remainders" asp-action="Index">Remainders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="StudyGroups" asp-action="Index">StudyGroups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="UserAvailabilities" asp-action="Index">UserAvailabilities</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="UserCourses" asp-action="Index">UserCourses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="UserStudyGroups" asp-action="Index">UserStudyGroups</a>
                    </li>
                    <br>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="RoleWithinGroup" asp-action="Index">RoleWithinGroup</a>
                    </li>
                    <partial name="_LanguageSelectionPartial"/>
                </ul>
                
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
}
else
{
    
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container header">
                    <a class="navbar-brand" href="/">SGF</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/test">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/StudyGroupsPublic">StudyGroups</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/myhub">Chats</a>
                            </li>
                            <partial name="_LanguageSelectionPartial"/>
                        </ul>
                        <partial name="_LoginPartial"/>
                    </div>
                </div>
            </nav>
}
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>